version: "3"
services:
  app:
    build: .
    restart: always
    container_name: business-card
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.business-card.entrypoints=web,websecure"
      - "traefik.http.routers.business-card.rule=Host(`card.freezingkas.com`)"
      - "traefik.http.services.business-card.loadbalancer.server.port=8000"
      - "traefik.http.routers.business-card.tls=true"
      - "traefik.http.routers.business-card.tls.certresolver=lets-encrypt"

networks:
  web:
    external: true
